\c curriculo
SET ROLE dba;
DROP TABLE IF EXISTS curriculo CASCADE;
DROP TABLE IF EXISTS trilha CASCADE;
DROP TABLE IF EXISTS modulo CASCADE;
DROP TABLE IF EXISTS disciplina CASCADE;
DROP TABLE IF EXISTS cur_tril CASCADE;
DROP TABLE IF EXISTS dis_mod CASCADE;
DROP TABLE IF EXISTS trilha_extrareqs CASCADE;
DROP TABLE IF EXISTS disciplina_requisitos  CASCADE;
DROP TABLE IF EXISTS disciplina_biblio CASCADE;
