\c pessoa
SET ROLE dba;

DROP TABLE IF EXISTS pessoa CASCADE;
DROP TABLE IF EXISTS aluno CASCADE;
DROP TABLE IF EXISTS professor CASCADE;
DROP TABLE IF EXISTS administrador CASCADE;
DROP TABLE IF EXISTS ministra CASCADE;
DROP TABLE IF EXISTS cursa CASCADE;
