/* Usuario q executa este script eh super user*/
CREATE ROLE dba
	WITH SUPERUSER CREATEDB CREATEROLE
	LOGIN ENCRYPTED PASSWORD 'dba1234'
	VALID UNTIL '2019-08-01';
CREATE ROLE aluno 
	LOGIN ENCRYPTED PASSWORD 'aluno'
	VALID UNTIL '2019-08-01';
CREATE ROLE professor 
	LOGIN ENCRYPTED PASSWORD 'prof'
	VALID UNTIL '2019-08-01';
CREATE ROLE admin 
	LOGIN ENCRYPTED PASSWORD 'admin'
	VALID UNTIL '2019-08-01';
CREATE ROLE guest 
	LOGIN ENCRYPTED PASSWORD 'guest'
	VALID UNTIL '2019-08-01';

CREATE DATABASE acesso OWNER dba;
CREATE DATABASE curriculo OWNER dba;
CREATE DATABASE pessoa OWNER dba;
CREATE DATABASE inter_pes_cur OWNER dba;
CREATE DATABASE inter_ace_pes OWNER dba;

GRANT guest to dba,aluno,professor,admin;
